In [2]:
%pip uninstall -y matplotlib seaborn

Found existing installation: matplotlib 3.11.1
Note: you may need to restart the kernel to use updated packages.

error: uninstall-no-record-file

Cannot uninstall matplotlib 3.11.1

The package's contents are unknown: no RECORD file was found for matplotlib.

hint: You might be able to recover from this via: pip install --force-reinstall --no-deps matplotlib==3.11.1

In [1]:
import pandas as pd

# 1. working with json

In [7]:
pd.read_json('test.json.zip')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [8]:
pd.read_json('https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json')

,name,language,id,bio,version
0,Adeel Solangi,Sindhi,V59OF92YF627HFY0,Donec lobortis eleifend condimentum. Cras dict...,6.10
1,Afzal Ghaffar,Sindhi,ENTOCR13RSCLZ6KU,"Aliquam sollicitudin ante ligula, eget malesua...",1.88
2,Aamir Solangi,Sindhi,IAKPO3R4761JDRVG,Vestibulum pharetra libero et velit gravida eu...,7.27
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49
...,...,...,...,...,...
192,Kristín Sigurðardóttir,Icelandic,ZP5TBBYX6RI2UJ31,Cras dictum dolor lacinia lectus vehicula rutr...,2.80
193,Rohini Vasav,Hindi,UEFML43TCGS04KWM,"Ut accumsan, est vel fringilla varius, purus a...",9.30
194,Sunil Kapoor,Hindi,VY2A0APGVHK5NAW2,"Proin tempus eu risus nec mattis. Ut dictum, l...",8.04
195,Zamokuhle Zulu,isiZulu,XU7BX2F8M5PVZ1EF,Etiam congue dignissim volutpat. Phasellus tin...,8.39
196,Bhupesh Menon,Hindi,0CEPNRDV98KT3ORP,Maecenas tempus neque ut porttitor malesuada. ...,2.69

# 2. working with sql

In [9]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 1.8 MB/s eta 0:00:07
     --- ------------------------------------ 1.0/11.9 MB 2.2 MB/s eta 0:00:05
     ----- ---------------------------------- 1.6/11.9 MB 2.3 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.4 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/11.9 MB 2.6 MB/s eta 0:00:04
     ----------- ---------------------------- 3.4/11.9 MB 2.7 MB/s eta 0:00:04
     ------------- -------------------------- 3.9/11.9 MB 2.7 MB/s eta 0:00:03
     --------------- ------------------------ 4.5/11.9 MB 2.7 MB/s eta 0:00:03
     ----------------- ---------------------- 5.2/11.9 MB 2.7 MB/s eta 0:00:03
     ------------------- -------------------- 5.8/11.9 MB 2.8 MB/s eta 0:00:03
     --------------------- ------------------ 6.3/11.9 MB 2.6 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.6 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.5 MB/s eta 0:00:02
     ------------------------- -------------- 7.6/11.9 MB 2.5 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 2.5 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 2.5 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.4 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 2.3 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.3 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 2.3 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 2.3 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 2.3 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.2 MB/s  0:00:05
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=f166d944ed137f324a149da091e6d74baf22660898fbd12725390e4db2b902b8
  Stored in directory: c:\users\kritika\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

WARNING: Ignoring invalid distribution ~atplotlib (L:\New folder\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (L:\New folder\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (L:\New folder\Lib\site-packages)

In [10]:
import mysql.connector

In [19]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

ProgrammingError: 1049 (42000): Unknown database 'world'